[package]
name = "image_manipulation_nannou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
nannou_osc = "0.18"
nannou_egui = "0.5.0"
